function [xsquare,ysquare] = bounddomain(lon,lat);
[Mp,Lp]=size(lon);
imin=1;
imax=Lp;
jmin=1;
jmax=Mp;
xsquare=cat(1,lon(jmin:jmax,imin),  ...
                lon(jmax,imin:imax)' ,...
                lon(jmax:-1:jmin,imax),...
                lon(jmin,imax:-1:imin)' );
ysquare=cat(1,lat(jmin:jmax,imin),  ...
                lat(jmax,imin:imax)' ,...
                lat(jmax:-1:jmin,imax),...
                lat(jmin,imax:-1:imin)' );
%h=plot(xsquare,ysquare,'-k');
return
